### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by AidenDe1** [bp3d-actions/workflows#1]
Hi, If it's alright, I was just wondering if I could ask you some questions about something. I tried emailing you at yuri6037@outlook.com around a month ago, which I found from that Zulip chat group, but I didn't get a response, so I thought I could try contacting you here 

Thanks in advance!

(sorry it's not a real issue or something about your code)

**Comment by Yuri6037** [comment]
I'm sorry but if it's not related to the workflows available in this repository, I'm gonna have to close the issue.

**Comment by AidenDe1** [comment]
oh ok no problem, i completely understand, would there be a better way to contact you?

**Comment by Yuri6037** [comment]
Please send an email.

**Comment by AidenDe1** [comment]
alright thanks, should i write to yuri6037@outlook.com?

**Comment by Yuri6037** [comment]
yes

**Comment by AidenDe1** [comment]
ok i sent you a message
